spring:
  datasource:
    name: mydb
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.94.162.137:3306/wuzu?useUnicode=true&characterEncoding=utf-8
    username: wuzu
    password: wuzu
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapperLocations: classpath*:mybatis/mapper-*.xml
  typeAliasesPackage: com.jk.bean
